default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user_post_crud_development

test:
  <<: *default
  database: user_post_crud_test

production:
  <<: *default
#  database: user_post_crud_production
#  username: user_post_crud
#  password: <%#= ENV["USER_POST_CRUD_DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>